# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/presence_tracing.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/presence_tracing.proto", :syntax => :proto3) do
    add_message "corona_presence_tracing.QRCodePayload" do
      optional :version, :uint32, 1
      optional :locationData, :message, 2, "corona_presence_tracing.TraceLocation"
      optional :crowdNotifierData, :message, 3, "corona_presence_tracing.CrowdNotifierData"
      optional :vendorData, :bytes, 4
    end
    add_message "corona_presence_tracing.TraceLocation" do
      optional :version, :uint32, 1
      optional :description, :string, 2
      optional :address, :string, 3
      optional :startTimestamp, :uint64, 5
      optional :endTimestamp, :uint64, 6
    end
    add_message "corona_presence_tracing.CrowdNotifierData" do
      optional :version, :uint32, 1
      optional :publicKey, :bytes, 2
      optional :cryptographicSeed, :bytes, 3
      optional :type, :uint32, 4
    end
    add_message "corona_presence_tracing.CWALocationData" do
      optional :version, :uint32, 1
      optional :type, :enum, 2, "corona_presence_tracing.TraceLocationType"
      optional :defaultCheckInLengthInMinutes, :uint32, 3
    end
    add_enum "corona_presence_tracing.TraceLocationType" do
      value :LOCATION_TYPE_UNSPECIFIED, 0
      value :LOCATION_TYPE_PERMANENT_OTHER, 1
      value :LOCATION_TYPE_TEMPORARY_OTHER, 2
      value :LOCATION_TYPE_PERMANENT_RETAIL, 3
      value :LOCATION_TYPE_PERMANENT_FOOD_SERVICE, 4
      value :LOCATION_TYPE_PERMANENT_CRAFT, 5
      value :LOCATION_TYPE_PERMANENT_WORKPLACE, 6
      value :LOCATION_TYPE_PERMANENT_EDUCATIONAL_INSTITUTION, 7
      value :LOCATION_TYPE_PERMANENT_PUBLIC_BUILDING, 8
      value :LOCATION_TYPE_TEMPORARY_CULTURAL_EVENT, 9
      value :LOCATION_TYPE_TEMPORARY_CLUB_ACTIVITY, 10
      value :LOCATION_TYPE_TEMPORARY_PRIVATE_EVENT, 11
      value :LOCATION_TYPE_TEMPORARY_WORSHIP_SERVICE, 12
    end
  end
end

module CoronaPresenceTracing
  QRCodePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("corona_presence_tracing.QRCodePayload").msgclass
  TraceLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("corona_presence_tracing.TraceLocation").msgclass
  CrowdNotifierData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("corona_presence_tracing.CrowdNotifierData").msgclass
  CWALocationData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("corona_presence_tracing.CWALocationData").msgclass
  TraceLocationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("corona_presence_tracing.TraceLocationType").enummodule
end
