.default-tags:
  tags: [ruby-2.5]

.bundle: &bundle
  - bundle config set --local with development
  - bundle install -j $(sysctl -n hw.ncpu)

rubocop:
  extends: .default-tags
  before_script:
    - *bundle
  script:
    - rubocop

specs:
  before_script:
    - *bundle
  script:
    - rspec
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"
    expose_as: 'SimpleCov report'
    paths:
      - 'coverage/'
    expire_in: 1 week
