require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'lib/corona_presence_tracing/proto/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
